apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: acme-corp
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./acme/org.yaml
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: backstage
spec:
  profile:
    email: armandocomellas@gmail.com
  memberOf:
    - team-a